// Importações necessárias
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/header";
import Footer from "./components/Footer/footer";

// Importação do script atualizado

// Configuração da fonte Inter
const inter = Inter({ subsets: ["latin"] });

// Metadados da página
export const metadata: Metadata = {
  title: "Salesforce",
  description: "Generated by create next app",
};

// Componente de layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <script src="../public/script/clicktracker"></script>
        <Footer />
      </body>
    </html>
  );
}
